services:
  - type: web
    name: krushiyuga-web-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false # This will be set manually in Render dashboard
    domains:
      - krushiyuga-web-app.onrender.com
